// ============================================================
// Mock data for static export / GitHub Pages demo
// Used when NEXT_PUBLIC_MOCK_MODE === 'true'
// ============================================================

import type { Product, Order, AnalyticsSummary, OrderStatus } from '@/types';

const now = new Date().toISOString();

function makeProduct(
  id: string,
  slug: string,
  name: string,
  brand: string,
  category: string,
  description: string,
  shortDescription: string,
  priceNet: number,
  stock: number,
  imageUrl: string,
): Product {
  const price = Math.round(priceNet * 1.21 * 100) / 100;
  return {
    id,
    slug,
    name,
    brand,
    description,
    shortDescription,
    price,
    priceNeto: priceNet,
    ivaRate: 0.21,
    category,
    images: [
      { id: `${id}-img-0`, url: imageUrl, alt: name, isPrimary: true, sortOrder: 0 },
    ],
    stock,
    sku: `BS-${id.toUpperCase()}`,
    tags: [],
    isActive: true,
    isFeatured: true,
    createdAt: now,
    updatedAt: now,
  };
}

export const MOCK_PRODUCTS: Product[] = [
  makeProduct(
    'p1',
    'serum-acido-hialuronico',
    'Sérum Ácido Hialurónico Puro',
    'Beauty Lash',
    'facial',
    'Sérum facial de ácido hialurónico puro al 2% para una hidratación profunda. Fórmula ligera que penetra rápidamente en la piel, rellenando líneas finas y aportando luminosidad. Apto para todo tipo de pieles.',
    'Hidratación profunda con ácido hialurónico al 2%',
    24.79,
    150,
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
  ),
  makeProduct(
    'p2',
    'crema-hidratante-rosa-mosqueta',
    'Crema Hidratante Rosa Mosqueta',
    'Beauty Lash',
    'facial',
    'Crema facial enriquecida con aceite de rosa mosqueta orgánico. Repara, nutre y protege la piel durante todo el día. Con vitamina E y extracto de aloe vera. Sin parabenos.',
    'Nutrición intensiva con rosa mosqueta orgánica',
    32.23,
    200,
    'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600',
  ),
  makeProduct(
    'p3',
    'mascarilla-arcilla-purificante',
    'Mascarilla de Arcilla Purificante',
    'NaturSkin',
    'facial',
    'Mascarilla facial de arcilla verde con carbón activo. Limpia los poros en profundidad, absorbe el exceso de grasa y devuelve un aspecto fresco y mate. Uso semanal recomendado.',
    'Limpieza profunda con arcilla verde y carbón activo',
    18.18,
    120,
    'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600',
  ),
  makeProduct(
    'p4',
    'aceite-corporal-argan-dorado',
    'Aceite Corporal de Argán Dorado',
    'Beauty Lash',
    'corporal',
    'Aceite corporal 100% natural de argán marroquí prensado en frío. Hidrata, suaviza y da luminosidad a la piel. Con partículas doradas para un acabado radiante. Perfecto para después de la ducha.',
    'Aceite de argán con partículas doradas',
    28.93,
    80,
    'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600',
  ),
  makeProduct(
    'p5',
    'balsamo-labial-cereza',
    'Bálsamo Labial Cereza Orgánico',
    'NaturSkin',
    'labios',
    'Bálsamo labial con extracto de cereza orgánica y manteca de karité. Hidrata, protege y da un toque de color natural a los labios. Con SPF 15. Sin ingredientes sintéticos.',
    'Hidratación labial con cereza orgánica y SPF 15',
    8.26,
    300,
    'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600',
  ),
  makeProduct(
    'p6',
    'contorno-ojos-antiedad-peptidos',
    'Contorno de Ojos Antiedad Péptidos',
    'Beauty Lash',
    'facial',
    'Crema contorno de ojos con péptidos bioactivos y cafeína. Reduce ojeras, bolsas e hinchazón. Fórmula ligera de rápida absorción con retinol encapsulado. Resultados visibles en 2 semanas.',
    'Anti-ojeras con péptidos y cafeína',
    36.36,
    90,
    'https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600',
  ),
  makeProduct(
    'p7',
    'champu-reparador-keratina',
    'Champú Reparador Keratina',
    'HairLux',
    'cabello',
    'Champú profesional con keratina hidrolizada para cabello dañado. Repara la fibra capilar desde el interior, aportando suavidad y brillo. Sin sulfatos ni siliconas. Apto para uso diario.',
    'Reparación capilar con keratina profesional',
    14.88,
    250,
    'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600',
  ),
  makeProduct(
    'p8',
    'parfum-flor-azahar',
    'Eau de Parfum Flor de Azahar',
    'Beauty Lash',
    'perfumería',
    'Perfume artesanal con notas de azahar de Sevilla, jazmín blanco y madera de sándalo. Fragancia fresca y sofisticada que evoca los jardines de Andalucía. Duración de hasta 8 horas.',
    'Fragancia artesanal de azahar sevillano',
    49.59,
    60,
    'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600',
  ),
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'BS-20260408-A1B2C3',
    userId: 'demo-user',
    status: 'delivered' as OrderStatus,
    items: [
      {
        id: 'oi-1',
        productId: 'p1',
        productName: 'Sérum Ácido Hialurónico Puro',
        productImage: '',
        sku: 'BS-P1',
        quantity: 2,
        priceNeto: 24.79,
        priceWithIva: 30.0,
        ivaRate: 0.21,
      },
      {
        id: 'oi-2',
        productId: 'p5',
        productName: 'Bálsamo Labial Cereza Orgánico',
        productImage: '',
        sku: 'BS-P5',
        quantity: 1,
        priceNeto: 8.26,
        priceWithIva: 10.0,
        ivaRate: 0.21,
      },
    ],
    shippingAddress: {
      calle: 'Calle Gran Vía 28',
      piso: '3º Izq',
      ciudad: 'Madrid',
      provincia: 'Madrid',
      codigoPostal: '28013',
      pais: 'España',
    },
    subtotalNeto: 57.84,
    ivaTotal: 12.16,
    shippingCost: 0,
    total: 70.0,
    paymentMethod: 'stripe',
    createdAt: '2026-04-08T10:30:00Z',
    updatedAt: '2026-04-09T14:20:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'BS-20260409-D4E5F6',
    userId: 'demo-user',
    status: 'in_transit' as OrderStatus,
    items: [
      {
        id: 'oi-3',
        productId: 'p2',
        productName: 'Crema Hidratante Rosa Mosqueta',
        productImage: '',
        sku: 'BS-P2',
        quantity: 1,
        priceNeto: 32.23,
        priceWithIva: 39.0,
        ivaRate: 0.21,
      },
    ],
    shippingAddress: {
      calle: 'Avinguda Diagonal 405',
      ciudad: 'Barcelona',
      provincia: 'Barcelona',
      codigoPostal: '08008',
      pais: 'España',
    },
    subtotalNeto: 32.23,
    ivaTotal: 6.77,
    shippingCost: 0,
    total: 39.0,
    paymentMethod: 'stripe',
    createdAt: '2026-04-09T09:15:00Z',
    updatedAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'order-3',
    orderNumber: 'BS-20260410-G7H8I9',
    userId: 'demo-user',
    status: 'processing' as OrderStatus,
    items: [
      {
        id: 'oi-4',
        productId: 'p8',
        productName: 'Eau de Parfum Flor de Azahar',
        productImage: '',
        sku: 'BS-P8',
        quantity: 1,
        priceNeto: 49.59,
        priceWithIva: 60.0,
        ivaRate: 0.21,
      },
    ],
    shippingAddress: {
      calle: 'Calle Sierpes 15',
      ciudad: 'Sevilla',
      provincia: 'Sevilla',
      codigoPostal: '41004',
      pais: 'España',
    },
    subtotalNeto: 49.59,
    ivaTotal: 10.41,
    shippingCost: 0,
    total: 60.0,
    paymentMethod: 'stripe',
    createdAt: '2026-04-10T11:45:00Z',
    updatedAt: '2026-04-10T11:45:00Z',
  },
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  totalOrders: 142,
  totalRevenue: 8745.50,
  activeProducts: 8,
  cartAbandonmentRate: 0.32,
  averageOrderValue: 61.59,
  salesOverTime: [
    { date: '2026-04-04', revenue: 980, orders: 18 },
    { date: '2026-04-05', revenue: 1240, orders: 22 },
    { date: '2026-04-06', revenue: 1100, orders: 19 },
    { date: '2026-04-07', revenue: 1580, orders: 27 },
    { date: '2026-04-08', revenue: 1320, orders: 23 },
    { date: '2026-04-09', revenue: 1450, orders: 25 },
    { date: '2026-04-10', revenue: 1075, orders: 8 },
  ],
  topProducts: [
    { productId: 'p1', productName: 'Sérum Ácido Hialurónico Puro', totalSold: 48, revenue: 1440 },
    { productId: 'p2', productName: 'Crema Hidratante Rosa Mosqueta', totalSold: 35, revenue: 1365 },
    { productId: 'p8', productName: 'Eau de Parfum Flor de Azahar', totalSold: 22, revenue: 1320 },
    { productId: 'p6', productName: 'Contorno de Ojos Antiedad Péptidos', totalSold: 28, revenue: 1232 },
    { productId: 'p4', productName: 'Aceite Corporal de Argán Dorado', totalSold: 24, revenue: 840 },
  ],
  dwellTimeByProduct: [
    { productSlug: 'serum-acido-hialuronico', productName: 'Sérum Ácido Hialurónico', avgDwellTimeMs: 45000, views: 320 },
    { productSlug: 'crema-hidratante-rosa-mosqueta', productName: 'Crema Rosa Mosqueta', avgDwellTimeMs: 38000, views: 280 },
    { productSlug: 'parfum-flor-azahar', productName: 'Parfum Flor Azahar', avgDwellTimeMs: 52000, views: 195 },
    { productSlug: 'contorno-ojos-antiedad-peptidos', productName: 'Contorno de Ojos', avgDwellTimeMs: 41000, views: 240 },
  ],
  orderStatusDistribution: {
    pending_payment: 8,
    processing: 22,
    ready_for_pickup: 5,
    shipped: 15,
    in_transit: 18,
    delivered: 68,
    cancelled: 4,
    refunded: 2,
  } as AnalyticsSummary['orderStatusDistribution'],
};
